name: build and deploy dockers
on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: is_docker
        run: docker -v
      - name: checkout
        uses: actions/checkout@v1
      - name: check list
        run: ls -a
      - name: build_docker
        run: docker build -t herrowpreeze/docker-react -f Dockerfile.dev .
      - name: start docker
        run: docker run herrowpreeze/docker-react npm run test -- --coverage